# Permalinks
permalink:        pretty

# Setup
url:              https://xingkongliang.github.io      

# Set to '' in case of hosting on `http://<your-github-name>.github.io`
baseurl:          /blog      

title:            xingkongliang

# Markdown enabled, however don't use more than one paragraph (enforced by `>`)
description:      >
    Sort my thoughts!

# The tags listed as entries in the sidebar
sidebar_tags:     [Deep Learning, Machine Learning, Algorithms, Life, Others]

# Fallback image and color if not overwritten for tag or post
image:            http://pic1.win4000.com/wallpaper/a/54584417cf961.jpg
color:            '#A85641'

# 阅读处理
safe:         false
include:      []
exclude:      ['README.md']
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

author:
  name:           'ZhangTianliang'
  twitter:        xingkongliang
  github:         xingkongliang
  photo:          http://www.ucassdl.cn/image/people/zhangtianliang.jpg

  # Markdown enabled, can use multiple paragraphs (enabled by `|`)
  about:  
    |
      Name: ZhangTianliang 

      Introduction: A UCAS student(master).

      Email: zhangtianliang13@mails.ucas.ac.cn

comments_sys: duoshuo
# comments_sys: disqus
comments: true